package Tema1Ejer2;

// 2. ¿Qué salida producirá el siguiente código?

// Error ya que 10 no es un Throwable

public class Ejercicio2 {
    /*
    public static void main(String[] args) {
        try {
            throw 10;
        }
        catch(int e) {
            System.out.println("Se produjo una excepción: " + e);
        }
    }
     */
}
